python3 -m torch.distributed.launch --nproc_per_node=8 run.py \
        --task generation \
        --model_name castorini/doc2query-t5-large-msmarco  \
        --per_device_eval_batch_size 16 \
        --run_name docTquery-NQ-generation \
        --max_length 512 \
        --valid_file /mnt/blob/v-binduan/NQ/Datasets/new_datasets/downloads/data/retriever/triviaqa_nci/Trivia_doc_content_v1.tsv \
        --output_dir temp \
        --dataloader_num_workers 10 \
        --report_to none \
        --logging_steps 100 \
        --num_return_sequences 15