python3 -m torch.distributed.launch --nproc_per_node=8 run.py \
        --task embedding \
        --model_name "castorini/doc2query-t5-large-msmarco" \
        --model_path models/nq_docTquery_t5_large/checkpoint-4800 \
        --per_device_eval_batch_size 4 \
        --run_name docTquery-NQ-generation \
        --max_length 96 \
        --valid_file /mnt/blob/v-binduan/NQ/Datasets/nq_preprocess/nq_doc_content.tsv \
        --output_dir temp \
        --dataloader_num_workers 10 \
        --report_to none \
        --logging_steps 100 \